# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce580314c45100a394af516854ca4eaf47199a3f202c337e7bad8d7ae338fdc0c2b3837dfe1b1cc78e1a8aae7d54b50f277b73e41e23e243699e54a4b4c78317

test:
  secret_key_base: 627060f5e927f455a0e1ec908b313f8feffc179cff5cbc7a113eec507052ceb8403902605be99b29653ca27d6937596b577f3c6322a2ca2e96dd369a3c544611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
